name = "demo-store"
compatibility_date = "2024-11-18"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

[[routes]]
pattern = "*"
zone_name = "kaffappliances.myshopify.com"

[vars]
PUBLIC_STOREFRONT_API_TOKEN = ""
PRIVATE_STOREFRONT_API_TOKEN = ""
PUBLIC_STORE_DOMAIN = "kaffappliances.myshopify.com"

# Optional: Add session configuration if needed
[durable_objects]
bindings = [
  # Add any durable objects if required
]

# Optional: KV namespace bindings
[[kv_namespaces]]
binding = "SESSION"
id = "your-kv-namespace-id"
preview_id = "your-preview-kv-namespace-id"